const scheduleData = {
    Monday: [
        {
            time: '8:00 AM - 10:00 AM',
            show: 'Morning Vibes',
            presenters: 'Jerry & Precious',
            hashtags: '#MorningShow #DailyNews',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '10:15 AM - 12:15 PM',
            show: 'Mid-Morning Groove',
            presenters: 'Viggy & Wahome',
            hashtags: '#MidMorningGroove #Tunes',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '12:30 PM - 2:30 PM',
            show: 'Afternoon Chill',
            presenters: 'LutherTheDJ & Miss Dawa',
            hashtags: '#AfternoonChill #Relax',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '3:00 PM - 5:00 PM',
            show: 'Evening Rush',
            presenters: 'Rootsy & Shaggy',
            hashtags: '#EveningRush #DailyWrapUp',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
    ],
    Tuesday: [
        {
            time: '8:00 AM - 10:00 AM',
            show: 'Morning Vibes',
            presenters: 'Jerry & Precious',
            hashtags: '#MorningShow #DailyNews',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '10:15 AM - 12:15 PM',
            show: 'Mid-Morning Groove',
            presenters: 'Viggy & Wahome',
            hashtags: '#MidMorningGroove #Tunes',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '12:30 PM - 2:30 PM',
            show: 'Afternoon Chill',
            presenters: 'LutherTheDJ & Miss Dawa',
            hashtags: '#AfternoonChill #Relax',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '3:00 PM - 5:00 PM',
            show: 'Evening Rush',
            presenters: 'Rootsy & Shaggy',
            hashtags: '#EveningRush #DailyWrapUp',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
    ],
    Wednesday: [
        {
            time: '8:00 AM - 10:00 AM',
            show: 'Morning Vibes',
            presenters: 'Jerry & Precious',
            hashtags: '#MorningShow #DailyNews',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '10:15 AM - 12:15 PM',
            show: 'Mid-Morning Groove',
            presenters: 'Viggy & Wahome',
            hashtags: '#MidMorningGroove #Tunes',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '12:30 PM - 2:30 PM',
            show: 'Afternoon Chill',
            presenters: 'LutherTheDJ & Miss Dawa',
            hashtags: '#AfternoonChill #Relax',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '3:00 PM - 5:00 PM',
            show: 'Evening Rush',
            presenters: 'Rootsy & Shaggy',
            hashtags: '#EveningRush #DailyWrapUp',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
    ],
    Thursday: [
        {
            time: '8:00 AM - 10:00 AM',
            show: 'Morning Vibes',
            presenters: 'Jerry & Precious',
            hashtags: '#MorningShow #DailyNews',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '10:15 AM - 12:15 PM',
            show: 'Mid-Morning Groove',
            presenters: 'Viggy & Wahome',
            hashtags: '#MidMorningGroove #Tunes',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '12:30 PM - 2:30 PM',
            show: 'Afternoon Chill',
            presenters: 'LutherTheDJ & Miss Dawa',
            hashtags: '#AfternoonChill #Relax',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '3:00 PM - 5:00 PM',
            show: 'Evening Rush',
            presenters: 'Rootsy & Shaggy',
            hashtags: '#EveningRush #DailyWrapUp',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
    ],
    Friday: [
        {
            time: '8:00 AM - 10:00 AM',
            show: 'Morning Vibes',
            presenters: 'Jerry & Precious',
            hashtags: '#MorningShow #DailyNews',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '10:15 AM - 12:15 PM',
            show: 'Mid-Morning Groove',
            presenters: 'Viggy & Wahome',
            hashtags: '#MidMorningGroove #Tunes',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '12:30 PM - 2:30 PM',
            show: 'Afternoon Chill',
            presenters: 'LutherTheDJ & Miss Dawa',
            hashtags: '#AfternoonChill #Relax',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '3:00 PM - 5:00 PM',
            show: 'Evening Rush',
            presenters: 'Rootsy & Shaggy',
            hashtags: '#EveningRush #DailyWrapUp',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
    ],
    Saturday: [
        {
            time: '8:00 AM - 10:00 AM',
            show: 'Weekend Start',
            presenters: 'Weekend Crew',
            hashtags: '#WeekendStart #FunTimes',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
        {
            time: '10:15 AM - 12:15 PM',
            show: 'Saturday Tunes',
            presenters: 'DJ Party & Crew',
            hashtags: '#SaturdayTunes #PartyVibes',
            image: 'src/assets/presenter.png',
            archiveLink: '#',
            moreInfoLink: '#',
        },
    ],
};

export default scheduleData;
